# Config example file to configure a data pipeline for the Standalone Environment.
#
# "interval", number of seconds between executions. Optional, default value 60.
# "exporter", string, where to export data. Possible values: "nrinfra", "nrmetrics", "nrevents", "nrlogs", "nrtraces", "otel" and "prom"
# "buffer", size of channel buffers. Optional, default value 100.

interval: 5
exporter: nrmetrics

# Custom keys here...

# Size of communication buffer between modules
# buffer: 500

# New Relic API credentials
nr_account_id: xxxxx
nr_user_key: xxxxx
nr_api_key: xxxxx
nr_endpoint: US
bitmovin_api_key: xxxxx
bitmovin_license_key: xxxxx
bitmovin_tenant_org: xxxxx

# Exporter batching and timing
# batch_size: 50
# harvest_time: 60